language: python
dist: xenial  # required for Python 3.7
sudo: true    # required for Python 3.7

python:
  - 3.7

matrix:
  allow_failures:
    - 3.7

services:
  - mongodb
  - redis-server

before_script:
  - pip install -U pip setuptools pytest flake8
  # trying to include unreleased fixes for pylint in combination w. Python 3.7
  - pip install --pre -U pylint astroid
  - pylint --rcfile=./pylintrc appkernel
  # stop the build if there are Python syntax errors or undefined names
  - flake8 ./appkernel --show-source --statistics --count
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
  - "pip install --editable ."
  - "pytest tests/ -s -v --capture=no"
  - "pylint appkernel"

before_deploy:
  - "python setup.py build -vf"

#  deploy:
#  - provider: pypi
#    user: $REPO_USER
#    password: $REPO_PASS
#    distributions: "bdist_wheel sdist"
